[workspace]

members = [
    "contest",
    "template",
]

exclude = [
    "fort",
    "ac-library-rs",
    "leetcode",
]

[profile.dev]
overflow-checks = false
[profile.test]
overflow-checks = false
