[workspace]

members = [
    "contest",
]

exclude = [
    "fort",
    "ac-library-rs",
    "leetcode",
    "lazy-static"
]

[profile.dev]
overflow-checks = false
[profile.test]
overflow-checks = false
