[package]
name = "contest"
version = "0.1.0"
edition = "2021"

[features]
"local-build" = []
"stress" = []

[profile.dev]
overflow-checks = false
opt-level = 0
[profile.test]
overflow-checks = false

[dependencies]